// Library seed data

export interface BookSeed {
  broj: number
  autor: string
  naslov: string
  izdavac: string
}

export interface JournalSeed {
  broj: number
  naslov: string
  svesci: string
}

export const BOOKS_SEED: BookSeed[] = [
  { broj:1, autor:"Iso Kršnjavi", naslov:"Kultura i politika na zidovima palače u Opatičkoj 10", izdavac:"Zagreb 2002" },
  { broj:2, autor:"Sebastijan Slade", naslov:"Dubrovačka kronika", izdavac:"Zagreb 2001" },
  { broj:3, autor:"L. Crijević Tuberon", naslov:"Komentari o mojem vremenu", izdavac:"Zagreb 2001" },
  { broj:4, autor:"Juraj Ratkaj", naslov:"Spomen na kraljeve i banove", izdavac:"Zagreb 2001" },
  { broj:5, autor:"Jakov Jelinčić", naslov:"Na postirskim vrelima", izdavac:"Postire 2004" },
  { broj:6, autor:"Oleg Mandić", naslov:"Kronika obitelji Mandić", izdavac:"Franjo Butorac" },
  { broj:7, autor:"dr sc Ivica Golec", naslov:"Petrinjski biografski leksikon", izdavac:"Petrinja 1999" },
  { broj:8, autor:"(zbornik radova)", naslov:"Petrovina i Volavje", izdavac:"Multigraf Zagreb" },
  { broj:9, autor:"dr sc Ante Gulin", naslov:"Hrvatska crkvena srednjovjekovna sfragistika", izdavac:"-" },
  { broj:10, autor:"prof dr sc Božena Vranješ Šoljan", naslov:"Stanovništvo gradova Banske Hrvatske na prijelazu stoljeća", izdavac:"Zagreb 1991" },
  { broj:11, autor:"Lovorka Čoralić", naslov:"U gradu Sv. Marka povijest hrv. zajednice u Mlecima", izdavac:"Zagreb 2001" },
  { broj:12, autor:"Ivankovic, Kraljevic, Mikulić", naslov:"Kocerin kroz stoljeća", izdavac:"Kočerin 2004" },
  { broj:13, autor:"Rummer, Branko, Hofbauer", naslov:"Lesebuch für allgemeine Volksschulen", izdavac:"1918" },
  { broj:14, autor:"dr sc Mate Matas", naslov:"Mućkolečevački prostor", izdavac:"Zagreb 1993" },
  { broj:15, autor:"V. Stipetić, N. Vekarić", naslov:"Povijesna demografija Hrvatske", izdavac:"Zagreb, Dubrovnik 2004" },
  { broj:16, autor:"N. Kapetanić, N. Vekarić", naslov:"Stanovništvo Konavala, 1", izdavac:"-" },
  { broj:17, autor:"N. Kapetanić, N. Vekarić", naslov:"Stanovništvo Konavala, 2", izdavac:"-" },
  { broj:18, autor:"N. Kapetanić, N. Vekarić", naslov:"Konavoski rodovi, 1", izdavac:"-" },
  { broj:19, autor:"N. Kapetanić, N. Vekarić", naslov:"Konavoski rodovi, 2", izdavac:"-" },
  { broj:20, autor:"N. Kapetanić, N. Vekarić", naslov:"Konavoski rodovi, 3", izdavac:"-" },
  { broj:21, autor:"N. Kapetanić, N. Vekarić", naslov:"Falsifikat o podrijetlu konavoskih rodova", izdavac:"-" },
  { broj:22, autor:"N. Vekarić", naslov:"Pelješki rodovi A - K", izdavac:"-" },
  { broj:23, autor:"N. Vekarić", naslov:"Pelješki rodovi L - Ž", izdavac:"-" },
  { broj:24, autor:"D. Gruber, V. Spinčić", naslov:"Povijest Istre", izdavac:"-" },
  { broj:25, autor:"Pavao Kutarčić", naslov:"Opcina i zupa Brdovec obiteljska rodoslovna stabla 1800-2002", izdavac:"Ključ Brdovecki 2004" },
  { broj:26, autor:"Branko Vujasinović", naslov:"Povijesni pregled građevne službe u Hrvatskoj od 1770.-1918.", izdavac:"Zagreb, 2002." },
  { broj:27, autor:"Pavao Kutarčić", naslov:"Rodoslovlje obitelji sela Ključ", izdavac:"-" },
  { broj:28, autor:"Dane Mataić Pavičić", naslov:"Hrvati u Čileu", izdavac:"-" },
  { broj:29, autor:"Edo Merlić", naslov:"Sv. Martin na Buzeštini", izdavac:"Pazin - Buzet 2006" },
  { broj:30, autor:"Pavao Maček", naslov:"Dva stara roda Zagrebacke zupanije (Mikulići, Crnkovečki)", izdavac:"-" },
  { broj:31, autor:"S. Marcec, M. Polic, Petar Strčić", naslov:"Lujo Margetić - život i djelo", izdavac:"-" },
  { broj:32, autor:"Zvonimir Erjavec", naslov:"Španovački rodoslov", izdavac:"Požega 2005" },
  { broj:33, autor:"Zvonimir Milčec", naslov:"Pozdravi doma - 101 zgoda", izdavac:"Bookovac 1990." },
  { broj:34, autor:"Ante Ivanković", naslov:"Podrijetlo hrvatskih rodova u Trilju i okolini", izdavac:"Trilj, 2000" },
  { broj:35, autor:"Ante Ivanković", naslov:"Duvanjska prezimena", izdavac:"Tomislavgrad, 2001" },
  { broj:36, autor:"Ante Ivanković", naslov:"Prezimena općine Dugopolje", izdavac:"Dugopolje, 2002" },
  { broj:37, autor:"Ante Ivanković", naslov:"Podrijetlo hrvatskih rodova vrličkog područja", izdavac:"MH Vrlika, 2003" },
  { broj:38, autor:"Ante Ivanković", naslov:"Podrijetlo hrvatskih rodova općine Otok na Cetini", izdavac:"Otok, 2004" },
  { broj:39, autor:"Ante Ivanković", naslov:"Podrijetlo hrvatskih rodova u Turjacima pokraj Sinja", izdavac:"MH Sinj, 2005" },
  { broj:40, autor:"Ante Ivanković", naslov:"Hrvatski rodovi u župi Podbablje", izdavac:"Split-Podbabije, 2005" },
  { broj:41, autor:"Ante Ivanković", naslov:"Hrvatski rodovi u župi Vinjani", izdavac:"Split-Vinjani, 2005" },
  { broj:42, autor:"Ante Ivanković", naslov:"Prezimena općine Dicmo", izdavac:"Dicmo, 2007" },
  { broj:43, autor:"Ante Ivanković", naslov:"Hrvatski rodovi općine Muć", izdavac:"Split, 2007" },
  { broj:44, autor:"Ante Ivanković", naslov:"Prezimena općine Lećevica", izdavac:"Split, 2007" },
  { broj:45, autor:"Hrvatski državni arhiv", naslov:"Pregled arhivskih fondova i zbirki RH - svezak 1.", izdavac:"Zagreb, 2006" },
  { broj:46, autor:"Branko Vujasinović", naslov:"Istaknute osobe u hrvatskom vodnom gospodarstvu kroz povijest", izdavac:"Zagreb, 2007" },
  { broj:47, autor:"Franjo Kozina", naslov:"Općina Radoboj", izdavac:"2007." },
  { broj:48, autor:"-", naslov:"1240-1990 Župa sv. Lovre Petrinja", izdavac:"Petrinja, 1990" },
  { broj:49, autor:"Josip Komorčec", naslov:"Bedekovčina 1727-1977", izdavac:"Bedekovčina 1977" },
  { broj:50, autor:"Dr sc Mladen Andreis", naslov:"Stanovnistvo Vinišca - povijesna antroponimija do 1900.", izdavac:"Trogir, 1988" },
  { broj:51, autor:"Dr sc Mladen Andreis", naslov:"Stanovnistvo Drvenika Ploca - do 1900.", izdavac:"M. H. Trogir, 2000" },
  { broj:52, autor:"Dr sc Mladen Andreis", naslov:"Stanovnistvo zupe Sv. Mihovila Arhandela u Trilju u 19. st.", izdavac:"Trogir, 2001" },
  { broj:53, autor:"Dr sc Mladen Andreis", naslov:"Trogirski patricijat u Srednjem vijeku", izdavac:"HAZU, 2002" },
  { broj:54, autor:"Dr sc Mladen Andreis", naslov:"Trogirsko plemstvo do kraja prve austrijske uprave", izdavac:"Trogir, 2006" },
  { broj:55, autor:"Ante Ukić", naslov:"Korijeni - demografska slika Srime", izdavac:"Zagreb, 2005" },
  { broj:56, autor:"Ante Ukić", naslov:"Stanovnistvo i obitelji otoka Prvica", izdavac:"Zagreb, 2005" },
  { broj:57, autor:"Ivan Jurić", naslov:"Genetičko porijeklo Hrvata", izdavac:"Sl. Dalmacija 2005" },
  { broj:58, autor:"Dr Juraj Kolarić", naslov:"Dvjesta Novokapelačkih proljeća", izdavac:"Zagreb 1977" },
  { broj:59, autor:"-", naslov:"Istarski zbornik", izdavac:"NZH 1949." },
  { broj:60, autor:"Adam grof Orsic Slavetićki", naslov:"Rod Oršića", izdavac:"HIBZ 1943." },
  { broj:61, autor:"-", naslov:"Zbornik 3-Grad Belišće - muzej 1884. - 2009.", izdavac:"Belišće 2009." },
  { broj:62, autor:"-", naslov:"Valpovački godišnjak br. 13", izdavac:"MH Valpovo 2008." },
  { broj:63, autor:"Božidar Ručević", naslov:"Znameni i podrijetlo roda Ručevića iz Starih Mikanovaca", izdavac:"Zagreb 2008" },
  { broj:64, autor:"Drago Brajdić", naslov:"Brajdić selo kroz stoljeća", izdavac:"Zagreb, 2008" },
  { broj:65, autor:"-", naslov:"Vrilo-2010. godišnjak župa Otočkog dekanata", izdavac:"Otočac, 2010." },
  { broj:66, autor:"Marijan Machala", naslov:"Oriovačke kronike", izdavac:"Zagreb, 2003" },
  { broj:67, autor:"-", naslov:"Buzetski zbornik, 29", izdavac:"Buzet, 2003" },
  { broj:68, autor:"-", naslov:"Buzetski zbornik, 30", izdavac:"Buzet, 2004" },
  { broj:69, autor:"-", naslov:"Zbornik o Zagori, 2", izdavac:"Zagreb, 1998" },
  { broj:70, autor:"-", naslov:"Zbornik o Zagori, 4 - Od Zagore do svjetskih metropola", izdavac:"Zagreb, 2001" },
  { broj:71, autor:"-", naslov:"Zaprešićki godišnjak, 2003", izdavac:"MH Zaprešić, 2004" },
  { broj:72, autor:"-", naslov:"Bibliografija zaprešičkog godišnjaka 1991. - 2002.", izdavac:"MH Zaprešić, 2004" },
  { broj:73, autor:"-", naslov:"Acta Keglevichiana (1322.-1527.)", izdavac:"Zagreb, 1917" },
  { broj:74, autor:"-", naslov:"Rijeka - godišnjak", izdavac:"Rijeka, 2005" },
  { broj:75, autor:"-", naslov:"Adresar hrvatskih ustanova i udruga izvan domovine", izdavac:"Hrv. svjet. kongres, 1996" },
  { broj:76, autor:"Drz. zavod za statistiku", naslov:"Imenik naselja RH - Abecedni popis naselja", izdavac:"Zagreb, 2002" },
  { broj:77, autor:"Drz. zavod za statistiku", naslov:"Imenik naselja KH - Sistematski popis naselja", izdavac:"Zagreb, 2002" },
  { broj:78, autor:"Drz. zavod za statistiku", naslov:"Popis stanovnistva 1991 - Narodnosni sastav", izdavac:"Zagreb, 1992" },
  { broj:79, autor:"Rep. zavod za statistiku", naslov:"Popis stanovništva 1991 - Naselja", izdavac:"Zagreb, 1992" },
  { broj:80, autor:"Rep. zavod za statistiku", naslov:"Popis stanovništva 1991 - Mjesne zajednice", izdavac:"Zagreb, 1992" },
  { broj:81, autor:"Peter Hawlina", naslov:"Rodoslovni priručnik", izdavac:"Rijeka, 2009" },
  { broj:82, autor:"Ivan Hojsak", naslov:"Rodoslovlje obitelji Drašković", izdavac:"Varaždin 2004" },
  { broj:83, autor:"Zlata Bujan Kovačević", naslov:"Bujani - price iz obiteljske kronike", izdavac:"MH Delnice" },
  { broj:84, autor:"Dr Hinko Freivogel", naslov:"Povijest porodice Freivogel", izdavac:"Staffelstein 1997" },
  { broj:85, autor:"Dr Hinko Freivogel", naslov:"Povijest porodice Freivogel (na njemačkom)", izdavac:"Staffelstein 1997" },
  { broj:86, autor:"Paver Gledec", naslov:"Pred zagonetkom obiteljskog stabla", izdavac:"Matis - Pregrada 2009" },
  { broj:87, autor:"Vinko Matošin", naslov:"Stanovništvo Primoštena u 19. stoljeću", izdavac:"MH Šibenik 2008" },
  { broj:88, autor:"Darinka Hanžek", naslov:"Baština - etnografski zapisi iz Gornjostubičkog kraja", izdavac:"D. i G. Stubica 2009" },
  { broj:89, autor:"-", naslov:"Putujući Slavonijom - godišnjak za 2009. godinu", izdavac:"Privlačica 2009." },
  { broj:90, autor:"Dr Josip Boesendorfer", naslov:"Agrarni odnosi u Slavoniji", izdavac:"Zagreb 1950." },
  { broj:91, autor:"-", naslov:"Vodic Zavoda za povijest hrv. književnosti, kazalista i glazbe", izdavac:"HAZU, Zagreb 2001" },
  { broj:92, autor:"Marko Tominac", naslov:"Tominac - Lika, Amerika, Slavonija (1989-2009)", izdavac:"Vinkovci 2009" },
  { broj:93, autor:"Rimac - Mladineo", naslov:"Zadarsko okružje na Mletačkom katastru iz 1709. godine", izdavac:"Drzavni arhiv u Zadru" },
  { broj:94, autor:"Ivan Lajic - Mario Bara", naslov:"Ratovi, kolonizacije i nacionalna struktura Slavonije u 20. st.", izdavac:"IMIN 2009." },
  { broj:95, autor:"Hrvoje Salopek", naslov:"Ogulinsko-modruški rodovi", izdavac:"Zagreb, 2007." },
  { broj:96, autor:"Zlata Bujan Kovačević", naslov:"Kovačevići - jedna zagrebačka građanska obitelj", izdavac:"Zagreb, 2005." },
  { broj:97, autor:"Milan pl. Vojnovich", naslov:"Bojevi u Lici, u ostaloj Hrvatskoj i Dalmaciji u godinu 1809.", izdavac:"Zagreb, 1907." },
  { broj:98, autor:"Ante Ukić", naslov:"Vodice u katastru prve polovice 19. stoljeća", izdavac:"Zagreb, 2010." },
  { broj:99, autor:"Božidar Ručević", naslov:"Podrijetlo Hrvata - povijesno i genetičko gledište", izdavac:"Zagreb, 2010." },
  { broj:100, autor:"Zlata Bujan Kovačević", naslov:"Fužinarski Bunjevci - priče iz rodoslovnog istraživanja", izdavac:"Delnice, 2010." },
  { broj:101, autor:"-", naslov:"Arhitektura, covjek, podneblje", izdavac:"Zagreb, 1978" },
  { broj:102, autor:"Ivan Čizmić", naslov:"Jugoslavenski iseljenički pokret u SAD", izdavac:"IHP, 1974." },
  { broj:103, autor:"Antun Cvitanić", naslov:"Srednjevjekovni statut bračke komune", izdavac:"Bracki zbornik, 1968." },
  { broj:104, autor:"-", naslov:"Statut grada Dubrovnika 1272.", izdavac:"Dubrovnik, 1990." },
  { broj:105, autor:"Lukša Beritić", naslov:"Utvrđenja grada Dubrovnika", izdavac:"Zagreb, 1953." },
  { broj:106, autor:"Rafaella Sarti", naslov:"Živjeti u kući - stanovanje, prehrana i odijevanje 1500.-1800.", izdavac:"Zagreb, 2006." },
  { broj:107, autor:"Svetislav Stjepan Krnjak", naslov:"Prilozi za proučavanje podrijetla roda Krnjak", izdavac:"Bjelovar, 2001." },
  { broj:108, autor:"Vjekoslav Klaić", naslov:"Povijest Bosne (fototip iz 1882.)", izdavac:"Sarajevo, 1990." },
  { broj:109, autor:"Vjekoslav Klaić", naslov:"Život i djela Pavla Rittera Vitezovića", izdavac:"Zagreb, 1914" },
  { broj:110, autor:"Rafo Bogišić", naslov:"Senjski zbornik 22 - Pavao Vitezović kao kroatist", izdavac:"Senj 1995." },
  { broj:111, autor:"-", naslov:"Otočki ljetopis - Cres, Ilovik, Lošinj...", izdavac:"1973." },
  { broj:112, autor:"Pavao Tijan", naslov:"Senjske štorije i ćakule", izdavac:"Zagreb, 1940." },
  { broj:113, autor:"-", naslov:"Jastrebarsko - Narodna nošnja, Časopis Kaj 6-8", izdavac:"1976." },
  { broj:114, autor:"-", naslov:"Historijski zbornik 1968. - 69.", izdavac:"Povjesno drustvo Hrvatske" },
  { broj:115, autor:"Robert Balogh", naslov:"Švapsko evanđelje", izdavac:"Zagreb, 2006." },
  { broj:116, autor:"Josip Butorac", naslov:"Kutina", izdavac:"Kutina, 1977" },
  { broj:117, autor:"-", naslov:"Zbornik Moslavine, knjiga 1.", izdavac:"1968." },
  { broj:118, autor:"Mladen Andreis", naslov:"Stanovništvo otoka Šolte do godine 1900.", izdavac:"Split 2011." },
  { broj:119, autor:"-", naslov:"Tkalčić - godišnjak društva za povjesnicu", izdavac:"Zagreb, 2010." },
  { broj:120, autor:"Stjepan Razum", naslov:"Vjeroispovijedi i župničke prisege Zagrebačke nadbiskupije", izdavac:"Zagreb, 2010." },
  { broj:121, autor:"Grupa autora", naslov:"Tragom naših predaka", izdavac:"Zagreb, 2011" },
  { broj:122, autor:"-", naslov:"Zaprešički godišnjak 2007.", izdavac:"Zaprešić 2008" },
  { broj:123, autor:"Pavao Maček, Ivan Jurković", naslov:"Rodoslov plemića i baruna Kaštelanovića od Svetog duha", izdavac:"Slavonski Brod 2009." },
  { broj:124, autor:"Franjo Maletić, Petar Šimunović", naslov:"Hrvatski prezimenjak (I, II, III)", izdavac:"-" },
  { broj:125, autor:"Ivan Šindija", naslov:"Bibinjski korijeni", izdavac:"Matica hrvatska Zadar 2003." },
  { broj:126, autor:"Ivan Jurić", naslov:"Genetičko podrijetlo Hrvata - Etnogeneza", izdavac:"Vlastita naklada 2003." },
  { broj:127, autor:"Ivan Jurić", naslov:"Geneticko podrijetio Hrvata", izdavac:"Slobodna Dalmacija 2005." },
  { broj:128, autor:"Ivan Jurić", naslov:"Podrijetlo Hrvata - Genetički dokazi autohtonosti", izdavac:"Nova stvarnost, 2011." },
  { broj:129, autor:"Milan Salajić", naslov:"Staro Belišće - kulturno povijesni vodić", izdavac:"Belišće 2012." },
  { broj:130, autor:"-", naslov:"Valpovački godišnjak 2009.", izdavac:"MH Valpovo" },
  { broj:131, autor:"-", naslov:"Valpovački godišnjak 2010.", izdavac:"MH Valpovo" },
  { broj:132, autor:"-", naslov:"Valpovački godišnjak 2012.", izdavac:"MH Valpovo" },
  { broj:133, autor:"-", naslov:'Družba "Braće Hrvatskog zmaja"', izdavac:'Družba "BHZ" 2012.' },
  { broj:134, autor:"Enver Ljubović", naslov:"Mjestopis Krivog puta", izdavac:"Senj, 2009." },
  { broj:135, autor:"Damir Badurina", naslov:"Lunjski libar", izdavac:"MH Novalja 2012." },
  { broj:136, autor:"Zbirka rukopisa NSK", naslov:"Pavao Ritter Vitezović - u povodi 300. obljetnice smrti", izdavac:"NSK, 2013." },
  { broj:137, autor:"Marsel Dupont", naslov:"Murat - konjanik, maršal, carski princ i kralj Napulja", izdavac:"HTZ-Zagreb 1944." },
  { broj:138, autor:"-", naslov:"Imenik: dostojanstvenika, cinovnika, i javnin službenika 1902.", izdavac:"Zemaljska vlada" },
  { broj:139, autor:"Marko Kostrenčić", naslov:"Hrvatska pravna povijest", izdavac:"Tiskara Kugli Zgb" },
  { broj:140, autor:"Ljelja Dobronić", naslov:"Klasična gimnazija u Zagrebu od 1607. do danas", izdavac:"Školska knjiga 2004." },
  { broj:141, autor:"-", naslov:"Đakovo - biskupski grad", izdavac:"Đakovo 1979." },
  { broj:142, autor:"-", naslov:"Križevački štatuti", izdavac:"Križevci, 1967." },
  { broj:143, autor:"Ivan Rogić", naslov:"Katedrala u Đakovu", izdavac:"Osijek 1932." },
  { broj:144, autor:"Željko Rapanić", naslov:"Solin - grad i spomenici", izdavac:"Solin, 2000." },
  { broj:145, autor:"Emil Laszowski", naslov:"Grad Ozalj i njegova okolina", izdavac:"Braca hrv.zmaja, 1929" },
  { broj:146, autor:"Mihovil Pavlinović", naslov:"Razgovori o hrvatstvu, srbstvu i jugoslavenstvu", izdavac:"Zagreb 1943." },
  { broj:147, autor:"Fra VI. Brusić", naslov:"Otok Rab geografski umjetnički pregled", izdavac:"Rab" },
  { broj:148, autor:"-", naslov:"Povijest (Jutarnji list svesci 7-14)", izdavac:"Jutarnji list" },
  { broj:156, autor:"-", naslov:"Anali Zavoda za povijesne znanosti JAZU Dubrovnik XIX-XX", izdavac:"Dubrovnik 1982." },
  { broj:157, autor:"Mirela Slukan Altić", naslov:"Povijesni atlas gradova - Bjelovar - I svezak", izdavac:"Drzavni arhiv Bjelovar" },
  { broj:158, autor:"Mirela Slukan Altić", naslov:"Povijesni atlas gradova - Sisak - II svezak", izdavac:"Državni arhiv Sisak" },
  { broj:159, autor:"-", naslov:"Katastar Istre 1817.-1960.", izdavac:"HDA 2001." },
  { broj:160, autor:"Paul Boppe", naslov:"Hrvatske pukovnije u Napoleonovoj velikoj armiji", izdavac:"Cerus 2004." },
  { broj:161, autor:"Petar Strčić", naslov:"Neum - zavičaj i zemlja Hrvata", izdavac:"Neum 1995." },
  { broj:162, autor:"Petar Strčić", naslov:"Na velikoj prekretnici - prvi hrv. zakon Istre", izdavac:"Kastav, 1996." },
  { broj:163, autor:"Ekrem Čaušević", naslov:"Autobiografija Osman-age Temišvarskog", izdavac:"Srednja Europa 2004." },
  { broj:164, autor:"Viktor Duruy", naslov:"Povijest Grčke", izdavac:"Zagreb, 2011." },
  { broj:165, autor:"Stipan Mišura", naslov:"Biser Uskoplja - crtice iz prošlosti župe sv. Ilije u Kandiji", izdavac:"2011." },
  { broj:166, autor:"Ferdo Čulinović", naslov:"Seljačke bune u Hrvatskoj", izdavac:"Naučna knjiznica 1951." },
  { broj:167, autor:"Ferdo Čulinović", naslov:"Državnopravna historija jugoslavenskih zemalja", izdavac:"Školska knjiga 1961." },
  { broj:168, autor:"Tomislav Markus", naslov:"Predstavke županija i gradova banske Hrvatske 1861.-1867.", izdavac:"HIP" },
  { broj:169, autor:"-", naslov:"Monografija - hrvatski školski muzej 1901. - 2001.", izdavac:"Zagreb, 2001." },
  { broj:170, autor:"Sonja Gačina", naslov:"Slavonija na starim zemljopisnim kartama", izdavac:"MS-Osijek 1887." },
  { broj:171, autor:"Ljubomir Antić", naslov:"Hrvati u Južnoj Americi do godine 1914.", izdavac:"Stvarnost 1991." },
  { broj:172, autor:"Ljubomir Antić", naslov:"Hrvati i Amerika", izdavac:"Zagreb, 1992." },
  { broj:173, autor:"Dane Mataić Pavičić", naslov:"Hrvati u Čileu", izdavac:"Zagreb, 1998." },
  { broj:174, autor:"Hrvoje Salopek", naslov:"Ogulinsko modruški rodovi", izdavac:"Zagreb, 2007." },
  { broj:175, autor:"Lojzo Butorac", naslov:"Život i djelo dr. Josipa Butorca 1905. - 1993.", izdavac:"Naklada Slap 2002." },
  { broj:176, autor:"Vladimir Rem", naslov:"Stari Brod", izdavac:"Slavonski Brod 1981." },
  { broj:177, autor:"Marko Perojević", naslov:"Petar Kružić - kapetan i knez grada Klisa", izdavac:"Zagreb, 1931." },
  { broj:178, autor:"Olga Maruševski", naslov:"Iso Kršnjavi kao graditelj", izdavac:"Zagreb, 1986." },
  { broj:179, autor:"Vjekoslav Prvčić", naslov:"Stara Koprivnica", izdavac:"Koprivnica, 1993." },
  { broj:180, autor:"-", naslov:"Zelina, časopis Kaj 7-8", izdavac:"1971." },
  { broj:181, autor:"Josip Martinović", naslov:"Lipovljani, 1770.- 1970.", izdavac:"Lipovljani, 1970." },
  { broj:182, autor:"Bare Poparić", naslov:"Pregled povijesti pomorstva I dio", izdavac:"MH 1932." },
  { broj:183, autor:"Janez Toplišek", naslov:"Rodoslovje", izdavac:"Ljubljana 2004" },
  { broj:184, autor:"Nenad Vekarić", naslov:"Vlastela grada Dubrovnika - Svezak 1.", izdavac:"Dubrovnik 2011." },
  { broj:185, autor:"Nenad Vekarić", naslov:"Vlastela grada Dubrovnika - Svezak 2. (A-L)", izdavac:"Dubrovnik 2011." },
  { broj:186, autor:"Božidar Ručević", naslov:"Croatan indijanci - od legende do istine", izdavac:"Split, 2014." },
  { broj:187, autor:"Vladimir Kalšan", naslov:"Židovi u Međimurju", izdavac:"MMČakovac 2006." },
  { broj:188, autor:"Petar Šimunović", naslov:"Naša prezimena porijeklo, značenje i rasprostranjenost", izdavac:"NZMH 1985" },
  { broj:189, autor:"Petar Šimunović", naslov:"Hrvatska prezimena", izdavac:"Zgb 2006" },
  { broj:190, autor:"Forum", naslov:"Čileanski pisci - potomci hrvatskih iseljenika", izdavac:"7,8 1997" },
  { broj:191, autor:"HAZU, Zavod Osijek", naslov:"Gimnazije u Osijeku 1729.- 2000.", izdavac:"Osijek 2001." },
  { broj:192, autor:"Damir Tadić", naslov:"Livanjski kaići - Prilozi rodoslovlja", izdavac:"Zgb 2013." },
  { broj:193, autor:"Lelja Dobronić", naslov:"Zagrebački Gornji grad - nekad i danas", izdavac:"Zgb 1983." },
  { broj:194, autor:"Krešimir Kovačić", naslov:"Priče iz starog Zagreba", izdavac:"GZH 1990" },
  { broj:195, autor:"Gordana Krizmanić", naslov:"Vinogora i okolica", izdavac:"Matis 2013." },
  { broj:196, autor:"-", naslov:"Valpovački godišnjak 2013.", izdavac:"MH Valpovo 2008." },
  { broj:197, autor:"Karl Marks", naslov:"-", izdavac:"Kultura 1950." },
  { broj:198, autor:"Ivanka Dlaka, D. Crnogaj", naslov:"Srednja škola Vrbovec - Prvih 50 godina", izdavac:"SŠV, 2013." },
  { broj:199, autor:"Berislav Čegelj", naslov:"Zvečajska kronika - prezime Čegalj", izdavac:"Zgb 2013." },
  { broj:200, autor:"-", naslov:"Valpovački godišnjak 2014.", izdavac:"MH Valpovo 2014." },
  { broj:201, autor:"-", naslov:"Valpovački godišnjak 2015.", izdavac:"MH Valpovo 2015." },
  { broj:202, autor:"Mirko Marković", naslov:"Kvarnersko primorje", izdavac:"Jesenski i Turk 2005." },
  { broj:203, autor:"Mirko Marković", naslov:"Dalmacija stanovništvo i naselja", izdavac:"Jesenski i Turk 2005." },
  { broj:204, autor:"Mirko Marković", naslov:"Ličani kroz povijest", izdavac:"Jesenski i Turk 2001." },
  { broj:205, autor:"Mirko Marković", naslov:"Hrvatsko Zagorje", izdavac:"Jesenski i Turk 2003." },
  { broj:206, autor:"Mirko Marković", naslov:"Istočna Slavonija", izdavac:"Jesenski i Turk 2003." },
  { broj:207, autor:"Mirko Marković", naslov:"Međimurje - stanovništvo i naselja", izdavac:"Jesenski i Turk 2003." },
  { broj:208, autor:"Mirko Marković", naslov:"Gorski Kotar - stanovništvo i naselja", izdavac:"Jesenski i Turk 2003." },
  { broj:209, autor:"Mirko Marković", naslov:"Hrvatske pokrajine", izdavac:"Jesenski i Turk 2003." },
  { broj:210, autor:"Mirko Marković", naslov:"Hrvatski otoci na Jadranu", izdavac:"Jesenski i Turk 2004." },
  { broj:211, autor:"Mirko Marković", naslov:"Stočarska kretanja na Dinarskim planinama", izdavac:"Jesenski i Turk 2003." },
  { broj:212, autor:"Ive Mažuran", naslov:"Srednjevjekovni Osijek", izdavac:"MH - Osijek" },
  { broj:213, autor:"Stanko Andrić", naslov:"Slavonija - sažeti vodič", izdavac:"Biblioteka 3-2-1 2004." },
  { broj:214, autor:"-", naslov:"Novi Vinodolski", izdavac:"Privredni vjesnik 1989." },
  { broj:215, autor:"Tomislav Đurić", naslov:"Godinu dana cerničkih narodnih običaja", izdavac:"1992." },
  { broj:216, autor:"Tomislav Đurić", naslov:"Iz prošlosti novogradiškog kraja", izdavac:"Varaždin 1974." },
  { broj:217, autor:"Feliks Valentić", naslov:"Naši ljudi i krajevi", izdavac:"1981." },
  { broj:218, autor:"Josip Butorac", naslov:"Kutina uz 200. obljetnicu župne crkve", izdavac:"KS 1977." },
  { broj:219, autor:"Josip Badalić", naslov:"Moslavačke razglednice", izdavac:"Nar. tiskara Kutina 1980." },
  { broj:220, autor:"Vladimir Rem", naslov:"Vinkovačka kronika", izdavac:"Tiskara 1983." },
  { broj:221, autor:"Dragutin Pasarić", naslov:"Vidici kutinski", izdavac:"Inter-ing 1997." },
  { broj:222, autor:"Igor Karaman", naslov:"Požega u srcu Slavonije", izdavac:'Naklada "Slap" 1997.' },
  { broj:223, autor:"Filip Potrebrica", naslov:"Tri stoljeća požeške gimnazije", izdavac:'Naklada "Slap" 1994.' },
  { broj:224, autor:"Mirela Slukan Antić", naslov:"Povijesna kartografija", izdavac:"Meridijani 2003." },
  { broj:225, autor:"Rudolf Horvat", naslov:"Povijest trgovine, obrta i industrije u Hrvatskoj", izdavac:"Agram 1994." },
  { broj:226, autor:"Željko Voborski", naslov:"Luka Ilić Oriovčanin", izdavac:"Daruvarska tiskara 1994." },
  { broj:227, autor:"Franjo Šanjek", naslov:"Bosansko humski krstijani u povijesnim vremenima", izdavac:"Barbat 2003." },
  { broj:228, autor:"-", naslov:"Zagreb 1941. 1945.", izdavac:"Spektar 1972." },
  { broj:229, autor:"-", naslov:"Senjski zbornik", izdavac:"Gradski muzej Senj 1965." },
  { broj:230, autor:"-", naslov:"Hrvatsko kolo 22", izdavac:"MH 1941." },
  { broj:231, autor:"Vladimir Dedijer", naslov:"Jugoslaevnsko albanski odnosi 1939-1948.", izdavac:"Borba 1949." },
  { broj:232, autor:"Zrinka Blažević", naslov:"Vitezovićeva Hrvatska između stvarnosti i utopije", izdavac:"Barbat 2002." },
  { broj:233, autor:"Drago Brajdić", naslov:"Rakovački rodovi - tragom povijesti", izdavac:"ITG 2014." },
  { broj:234, autor:"Ante Nazor", naslov:"Matična knjiga vjenčanih župe Jesenice 1736.-1830.", izdavac:"HDA 2012." },
  { broj:235, autor:"Mario Stipančević", naslov:"Neznani svijet Emila Laszowskog", izdavac:"HRD, Zagreb 2014." },
  { broj:236, autor:"-", naslov:"Zemljopisne karte Hrvatske (12)", izdavac:"-" },
  { broj:237, autor:"Stjepan Pavičić", naslov:"Podrijetlo naselja i govora u Slavoniji", izdavac:"Slavonica 1994" },
  { broj:238, autor:"Gordana Podobnik", naslov:"Zavičaju - baština ravnogorskog kraja", izdavac:"fotokopija" },
  { broj:239, autor:"Ante Sekulić", naslov:"Osobna imena, prezimena i nadimci bačkih Hrvata", izdavac:"Hrvatska riječ 2006." },
  { broj:240, autor:"Stjepan Sršen", naslov:"Popis sandžaka Požega 1579. (defter)", izdavac:"Osijek 2001." },
  { broj:241, autor:"Ive Mažuran", naslov:"Od turskog do suvremenog Osijeka", izdavac:"Osijek 1996." },
  { broj:242, autor:"Tomo Šalić", naslov:"Vinkovački leksikon", izdavac:"Vinkovci 2007." },
  { broj:243, autor:"Ive Mažuranić", naslov:"Stanovništvo i vlastelinstva u Slavoniji 1736.", izdavac:"Osijek 1993." },
  { broj:244, autor:"Branimir Baron Brljević", naslov:"Likovi moga doba", izdavac:"Binizapress 2002." },
  { broj:245, autor:"Ivan Meštrović", naslov:"Uspomene na političke ljude i događaje", izdavac:"NZMH 1993." },
  { broj:246, autor:"-", naslov:"Zbornik zagrebačke klasične gimnazije 1607.-1957.", izdavac:"Zagreb 1957." },
  { broj:247, autor:"-", naslov:"Stare karte sjeverne Hrvatske", izdavac:"-" },
  { broj:248, autor:"Edo Merlić", naslov:"Stanovništvo i migracije iz sjeverna Istre", izdavac:"Pazin - Buzet 2011." },
  { broj:249, autor:"Edo Merlić", naslov:"Buzetska priča o starim razglednicama", izdavac:"Pazin - Buzet 2009." },
  { broj:250, autor:"-", naslov:"Hrvatsko seljačko pjevačko društvo - 100 godina", izdavac:"NSK, Zagreb, 2007." },
  { broj:251, autor:"Domagoj Novosel", naslov:"Gračanska kronika", izdavac:"NSB, Zagreb, 2008." },
  { broj:252, autor:"H. Petric, D. Feletar", naslov:"Novi Zrin - Zrinska utvrda na Muri", izdavac:"Zagreb 2001." },
  { broj:253, autor:"Zlata Bujan Kovačević", naslov:"Fužinarski kaj", izdavac:"MH Delnice 1999." },
  { broj:254, autor:"-", naslov:"Povijesni spomenici grada Zagreba", izdavac:"-" },
  { broj:255, autor:"Dr. Neven Budak", naslov:"Gradovi varaždinske županije u srednjem vijeku", izdavac:"Koprivnica 1994." },
  { broj:256, autor:"-", naslov:"Antun Mihanović i njegovo djelo 1796. - 1996.", izdavac:"Zagreb, 1996" },
  { broj:257, autor:"Vjekoslav Noršić", naslov:"Povijest župe uznesenja bl. dj. Marije u Zlataru", izdavac:"Zlatar, 1994." },
  { broj:258, autor:"Dr. Josip Butorac", naslov:"Marija Bistrica", izdavac:"Marija Bistrica, 1996." },
  { broj:259, autor:"-", naslov:"Zagorski godišnjak 1973.", izdavac:"Krapina" },
  { broj:260, autor:"Drago Kozina", naslov:"Od Surmancza do Đurmanca", izdavac:"Durmanac 2008." },
  { broj:261, autor:"Tomislav Krpan", naslov:"Čudesna dolina - Pootrbljavljem...", izdavac:"Vinkovci 1995." },
  { broj:262, autor:"Dr. Josip Butorac", naslov:"Vrbovec i okolica (1134.-1984.)", izdavac:"Čakovac 1984." },
  { broj:263, autor:"-", naslov:"Ivanićgrad - prošlost i baština", izdavac:"1978" },
  { broj:264, autor:"Dr. Dragutin Feletar", naslov:"Podravina općine Koprivnica, Đurđevac i Ludbreg", izdavac:"Koprivnica 1989." },
  { broj:265, autor:"Ive Mažuran", naslov:"Stanovništvo Osijeka 1693.-1703.", izdavac:"Osijek 1974." },
  { broj:266, autor:"-", naslov:"Uvijek Osijek", izdavac:"Osijek 1992." },
  { broj:267, autor:"-", naslov:"Pozdrav iz Osijeka - razglednice do 1945.", izdavac:"Povijesni arhiv Osijeka" },
  { broj:268, autor:"-", naslov:"Karlovac 1579. - 1979.", izdavac:"Historijski arhiv 1979." },
  { broj:269, autor:"Dušan Kolundžija", naslov:"Kolundžija - istina, predanja i legende", izdavac:"Sombor, 2010." },
  { broj:270, autor:"Dr. Fadil Ademović", naslov:"Beznađe zla (intervjui)", izdavac:"Sarajevo 1997." },
  { broj:271, autor:"Vasja Butina", naslov:"Moj rodovnik - priručnik", izdavac:"Cankarjeva založba" },
  { broj:272, autor:"Šime Demo", naslov:"Kanonske vizitacije senjske i modruške biskupije", izdavac:"HIP 2007." },
  { broj:273, autor:"-", naslov:"Zbornik radova sa znanstvenog skupa - Slavonski Brod", izdavac:"Sl. Brod 2000." },
  { broj:274, autor:"Alois Mauc", naslov:"Tri perly charvatske osady na Morave", izdavac:"2016." },
  { broj:275, autor:"Božidar Ručević", naslov:"Hrvatska nacionalna genealogija", izdavac:"Split, 2017." },
  { broj:276, autor:"Mirko Marković", naslov:"Hrvatsko zagorje", izdavac:"-" },
  { broj:277, autor:"-", naslov:"Župa Gornje Prekrižje", izdavac:"-" },
  { broj:278, autor:"-", naslov:"Konoba drugačije Petrovsko", izdavac:"-" },
  { broj:279, autor:"-", naslov:"Oroslavlje - povijestni zapisi", izdavac:"-" },
  { broj:280, autor:"-", naslov:"Zelinska kronika", izdavac:"-" },
  { broj:281, autor:"Božidar Ručević", naslov:"Buđenje - hrv. rodoslovna dokumentacijska središnjica", izdavac:"Vlastita naklada" },
  { broj:282, autor:"Nikola Batušić", naslov:"Uspomene na rubu potkove", izdavac:"Profil" },
  { broj:283, autor:"-", naslov:"Botanicka putovanja D. Hirta po otoku Cresu", izdavac:"Viškovo 2008." },
  { broj:284, autor:"-", naslov:"Historija slikarstva od pećinskog do apstraktnog", izdavac:"Nolit 1965." },
  { broj:285, autor:"Bryan Sykes", naslov:"Sedam Evinih kćeri - Genetička povijest Europljana", izdavac:"Naklada Zadro 2002." },
  { broj:286, autor:"L. Luca Cavalli-Sforza", naslov:"Geni, narodi i jezici", izdavac:"Algoritam" },
  { broj:287, autor:"Dr. Peter J. D. Adamo", naslov:"Četiri krvne grupe za 4 načina prehrane", izdavac:"AGM Zagreb 2000." },
  { broj:288, autor:"-", naslov:"Knjiga bilježaka samostana Presvetog Trojstva u Brodu", izdavac:"Sl. Brod 1997." },
  { broj:289, autor:"Jürgen Schultze", naslov:"Devetnaesto stoljeće - Umjetnost u slici", izdavac:"Rijeka 1970." },
  { broj:290, autor:"Drago Brajdić", naslov:"Povijest Selišta Drežničkog", izdavac:"2016." },
  { broj:291, autor:"-", naslov:"Sveti Ivan Zelina - Sjećanje u razglednicama", izdavac:"MH-SIZ 2000." },
  { broj:292, autor:"-", naslov:"Sveti Ivan Zelina - osam stoljeća povijesti i kulture", izdavac:"MH-SIZ 2000." },
  { broj:293, autor:"-", naslov:"Hrvatski neretvanski zbornik 9/17", izdavac:"Zagreb, 2017." },
  { broj:294, autor:"Jasna Čapo", naslov:"Vlastelinstvo Cernik", izdavac:"IEF-1991" },
  { broj:295, autor:"Slavko Dakić", naslov:"Spisi o novoj zavičajnosti", izdavac:"Turistkomerc 1992" },
  { broj:296, autor:"-", naslov:"Nikola Škrlec Lomnički (1729.-1799.)", izdavac:"HAZU-1999" },
  { broj:297, autor:"Anica Baletić", naslov:"Stanovništvo Vukovara i vukovarskog kraja", izdavac:"Globus 1993" },
  { broj:298, autor:"Mirela Slukan", naslov:"Povijesna kartografija", izdavac:"Meridijani-2003" },
  { broj:299, autor:"Matija Piller", naslov:"Putovanje po Slavoniji 1782. godine", izdavac:"NZ Zrinski-1995" },
  { broj:300, autor:"Ferdo Juzbašić", naslov:"Spomenci - Vinkovci (knjiga 77)", izdavac:"Slavonica 1994." },
  { broj:301, autor:"Krunoslav Tkalac", naslov:"Babogredska kompanija", izdavac:"Slavonica 1995." },
  { broj:302, autor:"-", naslov:"Leksikon naselja Hrvatske", izdavac:"Mozaik knjiga" },
  { broj:303, autor:"-", naslov:"Granice Hrvatske sa zemljovidima", izdavac:"MUO 1993." },
  { broj:304, autor:"Ivan Marušić", naslov:"Kronika Krbave i Udbine kroz stoljeća", izdavac:"A.G. Matoš" },
  { broj:305, autor:"-", naslov:"Hrvatsko srednjovjekovlje", izdavac:"Š.K. 1997" },
  { broj:306, autor:"Ivan Martinović", naslov:"Iz povijesti Vojne krajine", izdavac:"Slavonica 1994." },
  { broj:307, autor:"Mirko Breyer", naslov:"Antun conte Zanović i njegovi sinovi", izdavac:"MH 1928." },
  { broj:308, autor:"Andrija Zidrum", naslov:"Počeci naselja i stanovništvo brodskog kraja", izdavac:"Sl. Brod 2001." },
  { broj:309, autor:"-", naslov:"Zbornik: Staroiransko podrijetlo Hrvata", izdavac:"ZGB 1999." },
  { broj:310, autor:"Ferdo Šišić", naslov:"Povijest Hrvata 600.-1526. I dio", izdavac:"T. Marjan 2004." },
  { broj:311, autor:"Ferdo Šišić", naslov:"Povijest Hrvata 1526.-1918. II dio", izdavac:"T. Marjan 2004." },
  { broj:312, autor:"-", naslov:"Zbornik za narodni život i običaje - Knjiga 53", izdavac:"Zagreb 1995." },
  { broj:313, autor:"Božena Vranješ Šoljan", naslov:"Stanovništvo gradova Banske Hrvatske (2X)", izdavac:"Š.K. 1991." },
  { broj:314, autor:"Ognjeslav Utješinović", naslov:"Kućne zadruge - Vojna krajina", izdavac:"Š.K. 1988." },
  { broj:315, autor:"HIP", naslov:"Marčanska biskupija - Habsburgovci...", izdavac:"HIP 2007." },
  { broj:316, autor:"Mirko Marković", naslov:"Stari Zagrepčani - Život od prapovijesti do 19. st.", izdavac:"Jesenski i Turk" },
  { broj:317, autor:"Gjuro Szabo", naslov:"Stari Zagreb", izdavac:"Delo 1971." },
  { broj:318, autor:"-", naslov:"Prva dalmatinsko hrv. slavonska izložba 1864.", izdavac:"Zagreb 1864." },
  { broj:319, autor:"Mladen Paver", naslov:"Pred zagonetkom obiteljskog stabla - rukopis", izdavac:"-" },
  { broj:320, autor:"-", naslov:"Čakavska rič (Duga Resa)", izdavac:"Split 1989." },
  { broj:321, autor:"-", naslov:"Monografija - Općina Cestica", izdavac:"T. Tiva" },
  { broj:322, autor:"Božica Brkan", naslov:"Oblizeki - Moslavina za stolom", izdavac:"Acomen" },
  { broj:323, autor:"-", naslov:"Grobnički zbornik", izdavac:"Rijeka 1998." },
  { broj:324, autor:"Emilij Laszowski", naslov:"Gorski kotar i Vinodol - knezovi Frankopani i Zrinski", izdavac:"MH 1921." },
  { broj:325, autor:"Brozo Brozović", naslov:"Vinidolska knežija i morska kupališta", izdavac:"Zagreb 1938." },
  { broj:326, autor:"Antun Burić", naslov:"Povijesna antroponimija Gorskog kotara", izdavac:"Rijeka 1979." },
  { broj:327, autor:"Ive Mažuran", naslov:"Stanovništvo Osijeka 1693.- 1703.", izdavac:"Osijek 1974." },
  { broj:328, autor:"Ive Mažuran", naslov:"Osnivanje Vojne granice u Slavoniji 1702. godine", izdavac:"Osijek 2005." },
  { broj:329, autor:"-", naslov:"Žene u seoskoj kulturi Panonije", izdavac:"Vinkovci 1980." },
  { broj:330, autor:"Dr. Josip Bösendorfer", naslov:"Osječki zbornik", izdavac:"Osijek 1948" },
  { broj:331, autor:"-", naslov:"Glasnik arhiva Slavonije i Baranje", izdavac:"Osijek 1995" },
  { broj:332, autor:"Stjepan Sršen", naslov:"Osječki ljetopisi 1686. - 1945.", izdavac:"Osijek 1993." },
  { broj:333, autor:"Ive Mažuran", naslov:"Povijesni izvori Slavonije, Baranje i Srijema 1390-1409", izdavac:"Osijek 2002." },
  { broj:334, autor:"Mirko Marković", naslov:"Slavonija - Povijest naselja i podrijetlo stanovništva", izdavac:"Golden M. 2002." },
  { broj:335, autor:"Feliks Valentić", naslov:"Zapisi iz novogradiškog kraja", izdavac:"N. Gradiška 1977." },
  { broj:336, autor:"-", naslov:"Prirodoslovna baština Slavonske Požege", izdavac:"Zbornik 1977." },
  { broj:337, autor:"Đuro Stanković Janko", naslov:"Lovstvo požeške kotline", izdavac:"Sl. Požega 1981." },
  { broj:338, autor:"-", naslov:"Nova Gradiška - informator", izdavac:"N. Gradiška 1977." },
  { broj:339, autor:"Jasna Čapo", naslov:"Vlastelinstvo Cernik - promjene na hrvatskom selu", izdavac:"IEF 1991." },
  { broj:340, autor:"Vinko Proštenik", naslov:"Zupa Jazavica - poceci zupe u Novskoj", izdavac:"MH Novska 2009." },
  { broj:341, autor:"Mijo Dukić", naslov:"Glina i okolica", izdavac:"Glina 1980." },
]

export const JOURNALS_SEED: JournalSeed[] = [
  { broj:1, naslov:"KAJ - Po dragom kraju - Zabok", svesci:"1/1980" },
  { broj:2, naslov:"KAJ - Po dragom kraju - Dugoselsko područje", svesci:"1/1981" },
  { broj:3, naslov:"KAJ - Po dragom kraju - Krapina", svesci:"1/1982" },
  { broj:4, naslov:"KAJ - Po dragom kraju - Križ i okolica", svesci:"1/1984" },
  { broj:5, naslov:"KAJ - Po dragom kraju - Pregrada i okolica", svesci:"1/1985" },
  { broj:6, naslov:"KAJ", svesci:"1/1984" },
  { broj:7, naslov:"KAJ", svesci:"1/1997" },
  { broj:8, naslov:"KAJ", svesci:"3-4/1998" },
  { broj:9, naslov:"KAJ - Ruožnik rieči (antologija)", svesci:"1999" },
  { broj:10, naslov:"KAJ", svesci:"4,5,6/1999" },
  { broj:11, naslov:"KAJ", svesci:"3, 4, 5, 6 / 2000" },
  { broj:12, naslov:"KAJ", svesci:"1, 2, 3, 4, 5, 6/2001" },
  { broj:13, naslov:"KAJ", svesci:"4,5/2002" },
  { broj:14, naslov:"KAJ", svesci:"4, 5, 6 / 2003" },
  { broj:15, naslov:"KAJ", svesci:"4-5/2004" },
  { broj:16, naslov:"KAJ", svesci:"4, 5, 6/2005" },
  { broj:17, naslov:"KAJ", svesci:"3, 4, 5, 6/2006" },
  { broj:18, naslov:"KAJ", svesci:"4-5, 6/2007" },
  { broj:19, naslov:"KAJ", svesci:"1,2/2008" },
  { broj:20, naslov:"KAJ", svesci:"1,2,3/2010" },
  { broj:21, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2 / 1995" },
  { broj:22, naslov:"HRVATSKO ZAGORJE", svesci:"4/1998" },
  { broj:23, naslov:"HRVATSKO ZAGORJE", svesci:"1,2 / 2001" },
  { broj:24, naslov:"HRVATSKO ZAGORJE", svesci:"1,2 / 2002" },
  { broj:25, naslov:"HRVATSKO ZAGORJE", svesci:"1,2 / 2003" },
  { broj:26, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2, 3, 4 / 2004" },
  { broj:27, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2, 3, 4 / 2005" },
  { broj:28, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2, 3, 4 / 2006" },
  { broj:29, naslov:"HRVATSKO ZAGORJE", svesci:"3,4 / 2007" },
  { broj:30, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2, 3, 4 / 2008" },
  { broj:31, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2, 3, 4 / 2009" },
  { broj:32, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2 / 2010" },
  { broj:33, naslov:"HRVATSKO ZAGORJE", svesci:"1, 2 / 2011" },
  { broj:34, naslov:"KORIJENI (list domovinske i iseljene Hrvatske)", svesci:"2005" },
  { broj:35, naslov:"OBZOR - glasilo općine Oriovac (Tko su šokci?)", svesci:"2005" },
  { broj:36, naslov:"MATICA GLINSKA", svesci:"13/2004" },
  { broj:37, naslov:"MATICA - mjesečna revija HM iseljenika", svesci:"4, 6, 7, 8, 9, 11, 12 / 2006" },
  { broj:38, naslov:"MATICA - mjesečna revija HM iseljenika", svesci:"1, 2/2007" },
  { broj:39, naslov:"MATICA - mjesečna revija HM iseljenika", svesci:"7,8 / 2008" },
  { broj:40, naslov:"NOVINE - glasilo hrvatsko švedskog društva", svesci:"2005, 2006, 2007, 2008" },
  { broj:41, naslov:"Glasnik Hrvatskog plemićkog zbora", svesci:"1, 2, 3, 5, 6, 7/1998 - 2009" },
  { broj:42, naslov:"Prilozi za zbornik plemičkih obitelji", svesci:"2006, 2009" },
  { broj:43, naslov:"VITEZOVIĆ - mjesečnik za genealogiju...", svesci:"6/1903 (Zagreb)" },
  { broj:44, naslov:"VITEZOVIĆ - mjesečnik za genealogiju...", svesci:"8/1904 (Zagreb)" },
  { broj:45, naslov:"GRB I ZASTAVA", svesci:"broj 0 - 22 (2006.- 2017.)" },
  { broj:46, naslov:"Senjski zbornik", svesci:"29, 31, 32, 33, 34, 36, 37 i 38." },
  { broj:47, naslov:"Meridijani", svesci:"65, 76, 95, 98, 107, 108, 109, 111, 115, 118, 121" },
]
